- name: If the condition is true, then only execute the task.
  hosts: local
  connection: local
  vars:
    IS_LIVE: true
  tasks:
  - name: Execute the tast if condition is true
    ansible.builtin.debug:  
      msg: "Yes, it is Live"
    when: IS_LIVE