- name: Gathering facts
  hosts: local
  connection: local
  tasks:
  - name: Print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: check if the OS is REDHAT
    ansible.builtin.debug:
      msg: "Yes package manager is REDHAT"
    when: ansible_facts.os_family  == "RedHat"  

  - name: check if the OS is Debian
    ansible.builtin.debug:
      msg: "Yes package manager is Debian"
    when: ansible_facts.os_family  == "Debian"  